### ISSUE TITLE
add number to pages

### ISSUE THREAD

**Issue by rettinghaus** [cemfi/measure-detector#8]
It would be nice to have `@n` attributes on `<pb>` (for working manually with the file).

**Comment by sonovice** [comment]
In practice, this tool is used pretty often for scores that do not start on page 1. Therefore I would prefer to keep it as is to avoid manual corrections.

Adding the `@n` attribute, however, should be fairy simple: Add a counter before line 202 in [App.vue](https://github.com/cemfi/measure-detector/blob/3b04c844d35f90c2b1ba7f1ced0783cca2845b79/src/App.vue#L202) and keep track of it inside the `forEach` loop.

If I find some time, I will add an option pane for things like this in the future.

**Comment by sonovice** [comment]
Hmm, after thinking about it some more, we also have automatic measure numbering which oftentimes is off by a certain offset. Removing such numbers is less work than adding them, so I will look into it later today.

**Comment by sonovice** [comment]
Done in cc2c65356303d903c621de546598ad3fe22302ce.
